
@server = http://localhost:4004 

POST {{server}}/odata/v4/supplier/getSupplier
headers: 
      Content-Type: application/json

{
        "pID" : "1000010004"
}

####################################################
